### ISSUE TITLE
Decryption Error

### ISSUE THREAD

**Issue by NoFairPlay** [190nm/rein-kuro#4]
Hello, I'm very new to this, but I tried to follow the steps as best I could, but when I tried to execute the decryption command, I received this error. I've installed the most recent Visual Studio (2022) Python Development Tools.

**>>> [Warning] Cache revision None not found. <<<
Traceback (most recent call last):
  File "C:\Users\NoFairPlay\AppData\Local\Programs\Python\Python39\Scripts\reinkuro-script.py", line 33, in <module>
    sys.exit(load_entry_point('reinkuro==0.2.1', 'console_scripts', 'reinkuro')())
  File "C:\Users\NoFairPlay\AppData\Local\Programs\Python\Python39\lib\site-packages\reinkuro\octo.py", line 415, in main
    cli(__args__)
  File "C:\Users\NoFairPlay\AppData\Local\Programs\Python\Python39\lib\site-packages\reinkuro\octo.py", line 408, in cli
    export_all(current, localization=__args__.localization)
  File "C:\Users\NoFairPlay\AppData\Local\Programs\Python\Python39\lib\site-packages\reinkuro\octo.py", line 220, in export_all
    export_folder.joinpath("db.json").write_text(json.dumps(readable, sort_keys=True, indent=4))
  File "C:\Users\NoFairPlay\AppData\Local\Programs\Python\Python39\lib\pathlib.py", line 1285, in write_text
    with self.open(mode='w', encoding=encoding, errors=errors) as f:
  File "C:\Users\NoFairPlay\AppData\Local\Programs\Python\Python39\lib\pathlib.py", line 1252, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "C:\Users\NoFairPlay\AppData\Local\Programs\Python\Python39\lib\pathlib.py", line 1120, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: 'exports\\en\\v568_assets\\db.json'**

Update: Tried the Japanese version, still the same error as above.

**Comment by haiyang3-98** [comment]
I got the same error. The script is dumb. If there is no folder named v568_assets , instead of creating the folder it gives this error. So you just need to manually create a folder named v568_assets in  exports\en\
